Source/Web/DentistSpace.Web/Areas/Dentists/Controllers/RequestController.cs
namespace DentistSpace.Web.Areas.Dentists.Controllers
{
    using System.IO;
    using System.Web.Mvc;
    using Common;
    using Data.Models;
    using Infrastructure.ModelFilters;
    using Microsoft.AspNet.Identity;
    using Models.Requests;
    using Services.Contracts;
    using Web.Controllers;

    [Authorize(Roles = Roles.User)]
    public class RequestController : BaseController
    {
        private IDentistRequestService dentistRequests;
        private const string RequestsPath = "~/App_Data/uploads/dentistsRequests/";

        public RequestController(IDentistRequestService dentistRequests)
        {
            this.dentistRequests = dentistRequests;
        }

        [HttpGet]
        public ActionResult Index()
        {
            this.ViewBag.Title = "Make dentist request to admin!";
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModelState]
        public ActionResult Index(InputDentistRequestViewModel request)
        {
            if (request.File.ContentLength > 0)
            {
                var file = request.File;
                var fileExtension = Path.GetExtension(file.FileName);

                var dentistRequest = new DentistRequest()
                {
                    Content = request.Content,
                    UserId = this.User.Identity.GetUserId(),
                    Extension = fileExtension
                };

                this.dentistRequests.AddRequest(dentistRequest);

                var folder = dentistRequest.Id % 10;
                var realFileName = dentistRequest.FileName.ToString();

                var path = Path.Combine(this.Server.MapPath(RequestsPath + folder), realFileName + fileExtension);
                file.SaveAs(path);
            }
            else
            {
                this.TempData["ErrorMessage"] = "File can't be empty!";
            }

            //TODO: Write the right redirect view.
            return this.RedirectToAction("Index", "Home", new { area = string.Empty });
        }
    }
}

Source/Web/DentistSpace.Web/Controllers/BannerController.cs
namespace DentistSpace.Web.Controllers
{
    using System.Web.Mvc;
    using Data.Models;
    using Models.Home;
    using Services.Contracts;

    public class BannerController : BaseController
    {
        private IBannerService banners;

        public BannerController(IBannerService banners)
        {
            this.banners = banners;
        }

        // GET: Banner
        [ChildActionOnly]
        public ActionResult GetMainBanner()
        {
            var banner = this.banners.GetMainBanner();
            var result = this.Mapper.Map<BannerViewModel>(banner);
            if (result == null)
            {
                return this.Content("Main banner!");
            }

            return this.PartialView("_MainBannerPartial", result);
        }

        [ChildActionOnly]
        public ActionResult GetLeftBanner()
        {
            var banner = this.banners.GetLeftBanner();
            var result = this.Mapper.Map<BannerViewModel>(banner);
            if (result == null)
            {
                return this.Content("Left banner!");
            }

            return this.PartialView("_LeftBannerPartial", result);
        }

        [ChildActionOnly]
        public ActionResult GetBottomBanner()
        {
            var banner = this.banners.GetBottomBanner();
            var result = this.Mapper.Map<BannerViewModel>(banner);
            if (result == null)
            {
                return this.Content("Bottom banner!");
            }

            return this.PartialView("_BottomBannerPartial", result);
        }
    }
}

Source/Web/DentistSpace.Web/Controllers/CommunityController.cs
namespace DentistSpace.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Common;
    using Infrastructure.Constants;
    using Infrastructure.Populators;
    using Models.Posts;
    using Services.Contracts;

    [Authorize(Roles = Roles.Admin + ", " + Roles.Dentist)]
    public class CommunityController : BaseController
    {
        private IPostService posts;

        public CommunityController(IPostService posts)
        {
            this.posts = posts;
        }

        // GET: Community
        [PopulateCategories(CashingTime = CacheConstants.ShortCaching)]
        public ActionResult Index()
        {
            var posts = this.posts.GetAllPrivate();
            var result = this.Mapper.Map<IEnumerable<PostViewModel>>(posts);
            return this.View(result);
        }
    }
}

Source/Web/DentistSpace.Web/Controllers/PostsController.cs
namespace DentistSpace.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Infrastructure.Mapping;
    using Models.Home;
    using Models.Posts;
    using Services.Contracts;

    public class PostsController : BaseController
    {

        private IPostService posts;

        public PostsController(IPostService posts)
        {
            this.posts = posts;
        }

        // GET: Posts
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetPostsByCategoryId(int id)
        {
            var posts = this.posts.GetAllPublicByCategory(id);
            var result = this.Mapper.Map<IEnumerable<PostViewModel>>(posts);
            return this.PartialView("_PostsPartial", result);
        }

        [HttpGet]
        public ActionResult GetPrivatePostsByCategoryId(int id)
        {
            var posts = this.posts.GetAllPrivateByCategory(id);
            var result = this.Mapper.Map<IEnumerable<PostViewModel>>(posts);
            return this.PartialView("_PostsPartial", result);
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            var post = this.posts.GetPostDetails(id);
            var result = this.Mapper.Map<PostDetailsViewModel>(post);
            return this.View(result);
        }
    }
}

Source/Web/DentistSpace.Web/Views/Shared/_BottomBannerPartial.cshtml
@model DentistSpace.Web.Models.Home.BannerViewModel

<div class="row" style="height:125px; overflow:hidden; text-align:center;">
    <a href="@Model.CompanyUrl"><img src="@Model.ImageUrl" style="width:100%;" /></a>
</div>

Source/Web/DentistSpace.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/main")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/jquery")
    <script>
        (window.jQuery || document.write('<script src="/scripts/jquery-1.10.2.min.js"><\/script>'));
    </script>
    @RenderSection("kendoScripts", required: false)
</head>
<body>
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "brand-logo" })
                <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
                @Html.Partial("_LoginPartial")
                <ul class="right hide-on-med-and-down">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                    @if (User.IsInRole(DentistSpace.Common.Roles.User))
                    {
                        <li>@Html.ActionLink("Patient request", "Index", "Request", new { area = "Patients" }, null)</li>
                    }
                    @if (User.IsInRole(DentistSpace.Common.Roles.Dentist))
                    {
                        <li>@Html.ActionLink("Patient requests", "Requests", "Patients", new { area = "Dentists" }, null)</li>
                        <li>@Html.ActionLink("New post", "Create", "Posts", new { area = "Dentists" }, null)</li>
                        <li>@Html.ActionLink("Patient Documents", "Index", "Patients", new { area = "Dentists" }, null)</li>
                    }
                    @if (User.IsInRole(DentistSpace.Common.Roles.Dentist) || User.IsInRole(DentistSpace.Common.Roles.Admin))
                    {
                        <li>@Html.ActionLink("Community posts", "Index", "Community", new { area = "" }, null)</li>
                    }
                </ul>
                <ul class="side-nav" id="mobile">
                    @if (User.IsInRole(DentistSpace.Common.Roles.User))
                    {
                        <li>@Html.ActionLink("Patient request", "Index", "Request", new { area = "Patients" }, null)</li>
                    }

                    @if (User.IsInRole(DentistSpace.Common.Roles.Dentist))
                    {
                        <li>@Html.ActionLink("Patient requests", "Requests", "Patients", new { area = "Dentists" }, null)</li>
                        <li>@Html.ActionLink("New post", "Create", "Posts", new { area = "Dentists" }, null)</li>
                        <li>@Html.ActionLink("Patient Documents", "Index", "Patients", new { area = "Dentists" }, null)</li>
                    }
                    @if (User.IsInRole(DentistSpace.Common.Roles.Dentist) || User.IsInRole(DentistSpace.Common.Roles.Admin))
                    {
                        <li>@Html.ActionLink("Community posts", "Index", "Community", new { area = "" }, null)</li>
                    }
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container body-content">
        @Html.Action("GetMainBanner", "Banner", new { area = "" })
        @RenderBody()
        @Html.Action("GetBottomBanner", "Banner", new { area = "" })
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dentists app</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jqueryval")
    <script>
        ($.validator || document.write('<script src="/scripts/jquery.validate.min.js"><\/script>'));
    </script>
    @Scripts.Render("~/bundles/jqunobtrusive")
    <script>
        ($.validator.unobtrusive || document.write('<script src="/scripts/jquery.validate.unobtrusive.min.js"><\/script>'));
    </script>

    @Scripts.Render("~/bundles/modernizr")
    <script>
        (window.Modernizr || document.write('<script src="/scripts/modernizr-2.6.2.js"><\/script>'));
    </script>
    @Scripts.Render("~/bundles/respond")
    <script>
        (window.matchMedia || document.write('<script src="/scripts/respond.js"><\/script>'));
    </script>

    @Scripts.Render("~/bundles/materialize")
    <script>
        (Materialize || document.write('<script src="/scripts/materialize.min.js"><\/script>'))
    </script>

    @RenderSection("scripts", required: false)

    <script>
        $(".button-collapse").sideNav();
    </script>
</body>
</html>

Source/Web/DentistSpace.Web/Views/Shared/_MainBannerPartial.cshtml
@model DentistSpace.Web.Models.Home.BannerViewModel

<div class="row" style="height:125px; overflow:hidden; text-align:center;">
   <a href="@Model.CompanyUrl"><img src="@Model.ImageUrl" style="width:100%;"/></a>
</div>

Source/Web/DentistSpace.Web/Views/Shared/_PostsPartial.cshtml
@model IEnumerable<DentistSpace.Web.Models.Posts.PostViewModel>

<div class="row">
    @Html.DisplayForModel(Model)
</div>